export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_FAIL = "ALL_POST_FAIL";

export const OWNER_POST_REQUEST = "OWNER_POST_REQUEST";
export const OWNER_POST_SUCCESS = "OWNER_POST_SUCCESS";
export const OWNER_POST_FAIL = "OWNER_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const CREATE_POST_RESET = "CREATE_POST_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR"